#!/usr/bin/env python3
import json

def apply_puns():
    with open("QuestionBank/verified_clues.json", "r", encoding="utf-8") as f:
        clues = json.load(f)

    PUN_MAP = {
        "ALLIED OCCUPATION: WWII": "THE BRIDGE OF VICTORY ROAD",
        "AMIR KABIR'S REFORMS": "DAR AL-FUN-UN & GAMES",
        "ANCIENT WARFARE: EMPIRES AT CLASH": "THE 300 & THEN SOME",
        "BAZARIS & MERCHANTS": "BAZAAR-O WORLD",
        "CINEMA AFTER THE STORM": "COWS, CHERRIES & CELLULOID",
        "CLASSICAL PERSIAN MUSIC MASTERS": "BARBAD TO THE BONE",
        "CLERICAL POWER: MARAJE OF NAJAF AND QOM": "HAWZA LIFE TREATING YOU?",
        "COLD WAR ESPIONAGE IN TEHRAN": "THE SPY WHO LIKED KEBAB",
        "COURT, CLOTH & CONCESSIONS": "WE DON'T COTTON TO CONCESSIONS",
        "CUISINE OF THE PROVINCES": "TAHDIG YOUR OWN GRAVE",
        "DIPLOMATIC HIGH WIRE": "THE GREAT GAME OF THRONES",
        "ECONOMIC BOOM & PETRODOLLARS": "TWELVE DOLLARS A BARREL",
        "EXILE OF THE SHAH": "JOHANNESBURG BLUES",
        "FOUNDATIONS OF STATEHOOD": "ZAND OF HOPE & GLORY",
        "FROM THE SHAH'S DIARY": "DEAR DIARY: THE SHAH SPEAKS",
        "GEOGRAPHY OF THE REALM": "LUT'S GET PHYSICAL",
        "GOLDEN AGE: ISLAMIC SCIENCES": "AVICENNA & THE BRAINIACS",
        "HERITAGE OF THE CYLINDER": "CYRUS ON ROLLS",
        "HOSTAGE CRISIS: 444 DAYS": "DESERT ONE & DONE",
        "IDEAS THAT SHOOK TEHRAN": "GHARBZADEGI & GRIEVANCE",
        "ILKHANID & TIMURID RENAISSANCE": "STARS OVER MARAGHEH",
        "IRANIAN CINEMA: DIRECTORS AND AUTEURS": "DIRECTED BY KIAROSTAMI & CO.",
        "ISLANDS & PORTS OF THE SOUTH": "GULF OF PERSIA, NOT DISCORD",
        "MODERN PROSE & THE NOVEL": "ONCE UPON A JAMALZADEH",
        "MONUMENTS OF EMPIRE": "APADANA & APARTMENTS",
        "MUSIC: RADIF AND DASTGAH": "JUST FOR THE DASTGAH OF IT",
        "MYTHS & MONSTERS OF THE SHAHNAMEH": "ROSTAM'S SEVEN HABITS",
        "NEW WAVE POETRY: SHER-E NOW": "IT'S NIMA OR NEVER",
        "OIL, OBVIOUSLY": "OIL, OBVIOUSLY",
        "PARTHIAN ARROWS & SHADOWS": "TAKING A PARTHIAN SHOT",
        "PERSIAN GULF: TANKER WAR": "PRAYING MANTIS ON PATROL",
        "PHILOSOPHY OF ISFAHAN: THE METAPHYSICIANS": "MULLA SADRA'S SOUL FOOD",
        "PIONEERING WOMEN OF MODERN IRAN": "WOMEN WHO MOVED THE REALM",
        "PROVISIONAL REGIME: 1979": "BAZARGAN'S BLUNT BLADE",
        "REVOLUTIONARY TRIBUNALS": "KHALKHALI'S GAVEL DROPS",
        "ROYAL REVOLUTION": "THE SHAH'S SIX POINTS",
        "SACRED SHRINES & PILGRIMAGE": "QOM WHAT MAY",
        "SAVAK: THE EYE OF THE SHAH": "SAVAK TO THE FUTURE",
        "SHADOW WAR: 1953": "OPERATION AJAX & CLEANSER",
        "SHAHNAMEH & THE HEROES": "FERDOWSI'S RHYME TIME",
        "SHIRAZ: ROSES & NIGHTINGALES": "HAFIZ THE BEATLES OF SHIRAZ",
        "SWORD OF PERSIA": "NADER SHAH'S SWORDPLAY",
        "TABRIZ: PIVOT OF RESISTANCE": "SATTAR WARS: TABRIZ STRIKES BACK",
        "TEHRAN: BAZAAR TO MEGAPOLIS": "FROM VILLAGE TO VALIASR",
        "THE 1971 PERSEPOLIS GALA": "PARTY LIKE IT'S 539 BC",
        "THE ARCH OF CHOSROES": "VAULT OF CTESIPHON",
        "THE ASSASSIN OF THE MONARCH": "BULLET AT THE BAST",
        "THE BOMBARDMENT OF PARLIAMENT": "LIAKHOV'S CANNONS",
        "THE BORDER ON THE ARAS": "THALWEG BLUES",
        "THE CHORUS OF MARTYRS": "DEHKHODA'S DEAD CANDLE",
        "THE COLD WAR AT THE ARAS": "AZERBAIJAN CRISIS: 1946",
        "THE CONSTITUTIONALISTS": "A MASH-RUTEH MADE IN HEAVEN",
        "THE CRUCIBLE OF ISFAHAN": "ISFAHAN-TASTIC SAFFAVIDS",
        "THE FATE OF THE PREMIER": "FATEMI'S LAST STAND",
        "THE FIRST CONSTITUTION": "MOZAFFAR'S DYING STAMP",
        "THE FIRST SHAHNAMEH MILLENARY": "TUS MARBLE CONGRESS",
        "THE FIRST SOUND ACTRESS": "GOLNAR ON CELLULOID",
        "THE IRON COSSACK": "THE IRON COSSACK: REZA SHAH",
        "THE LEFT IN IRAN: GUERRILLAS": "SIAHKAL & HYDE",
        "THE OIL CRISIS: 1951-1953": "ABAPLAN GONE WRONG",
        "THE RETURN FLIGHT": "AIR FRANCE TO TEHRAN",
        "THE REVOLUTIONARY SOVEREIGN": "FEREYDUN'S OX-MACE",
        "THE REVOLUTIONARY YEAR: 1978": "1978: A REVOLUTION ODYSSEY",
        "THE ROYAL CORONATION JEWEL": "SEA OF LIGHT DIAMOND",
        "THE RUSSO-PERSIAN WARS": "TURKMEN-CHAY TEA PARTY",
        "THE SACRED DEFENSE": "DEFENSE OF THE REALM",
        "THE SACRED DEFENSE BALLET": "THE JAMEH RESISTANCE",
        "THE SACRED DEFENSE: BATTLEFIELDS": "FISH LAKE & TANK TRAPS",
        "THE SECRET BBC CODE PHRASE": "EXACTLY MIDNIGHT",
        "THE STRANGLING OF PERSIA": "SHUSTER'S INDICTMENT",
        "THE SUFI MYSTICS": "RUMI WITH A VIEW",
        "THE TOBACCO PROTEST FORENSICS": "SMOKE 'EM IF YOU'VE GOT 'EM",
        "THE TRANS-IRANIAN RAILWAY": "ALL ABOARD THE VERESK EXPRESS",
        "THE WHITE REVOLUTION IN DEPTH": "REVOLUTION OF THE SHAH & PEOPLE",
        "TRADITIONAL CRAFTS & MASTERS": "CARPET DIEM",
        "VOICES OF WOMEN": "LADIES OF THE CONSTITUTION",
        "WAR & LIBERATION": "KHORRAMSHAHR UNBOUND",
        "WAR DIARIES: FRONTLINE MEMOIRS": "CHESS WITH DOOMSDAY MACHINES",
        "WAR LITERATURE & CINEMA": "FROM KARKHEH WITH LOVE",
        "WHAT KHOMEINI ACTUALLY SAID": "WHAT KHOMEINI ACTUALLY SAID"
    }

    updated = 0
    for c in clues:
        cat = c["category"]
        if cat in PUN_MAP:
            c["category"] = PUN_MAP[cat]
            updated += 1

    print(f"Updated {updated} clues to punny category titles.")

    with open("QuestionBank/verified_clues.json", "w", encoding="utf-8") as f:
        json.dump(clues, f, indent=2, ensure_ascii=False)

    print(f"Successfully saved QuestionBank/verified_clues.json. Total clues: {len(clues)}")

if __name__ == "__main__":
    apply_puns()
