#!/usr/bin/env python3
"""Write out everything already on the board, for an author to read first.

The author of a batch never opens the archive — that is the rule that keeps it
safe, and it is also what makes a repeat likely. This closes the gap without
opening the archive to anyone: it reads the two archives and writes a flat,
readable index of what is taken.

    QuestionBank/BANK_DIGEST.md       the English board
    QuestionBank/BANK_DIGEST_fa.md    the Persian board

Each category is one block, each rung one line: the answer, then the clue it
was asked in. An author reads the block for the slot it is about to write and
can see at a glance what that slot already holds.

Both files are generated. Never edit them; run this again instead. The merge
command (`Tools/append_batch.py`) refuses a repeat anyway — the digest is what
stops an author from wasting a day finding that out.

    python3 Tools/bank_digest.py
    python3 Tools/bank_digest.py --lang fa

Read-only with respect to the archives.
"""

import argparse
import json
import os
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ARCHIVES = {
    "en": ("QuestionBank/verified_clues.json", "QuestionBank/BANK_DIGEST.md",
           "English"),
    "fa": ("QuestionBank/verified_clues_fa.json", "QuestionBank/BANK_DIGEST_fa.md",
           "Persian"),
}

ROUND_ORDER = {"single": 0, "double": 1, "final": 2}
GIST = 58  # characters of clue text carried, enough to recognise the question


def gist(text):
    text = " ".join((text or "").split())
    return text if len(text) <= GIST else text[:GIST - 1].rstrip() + "…"


def value_of(row):
    try:
        return int(str(row.get("value")).strip())
    except (TypeError, ValueError):
        return 0


def digest(lang, rows):
    src, dest, name = ARCHIVES[lang]
    by_cat = defaultdict(list)
    for row in rows:
        by_cat[(row.get("round") or "?", row.get("category") or "?")].append(row)

    lines = [
        "# What is already on the board — %s" % name,
        "",
        "%d clues in %d categories, read from `%s`." % (len(rows), len(by_cat), src),
        "Generated by `python3 Tools/bank_digest.py` — do not edit by hand.",
        "",
        "Everything below is taken. Before writing a clue, check it is not here:",
        "not the same answer, and not the same question in other words. The merge",
        "command refuses a repeat, so a batch that ignores this comes straight back.",
        "",
        "`_b`, `_encore` and similar suffixes in an id mean that slot already holds",
        "more than one question. A slot may hold any number; what it may not hold is",
        "the same question twice.",
        "",
    ]

    for rnd in sorted({r for r, _ in by_cat},
                      key=lambda r: ROUND_ORDER.get(r, 9)):
        lines.append("## %s" % rnd.upper())
        lines.append("")
        cats = sorted([k for k in by_cat if k[0] == rnd], key=lambda k: k[1].lower())
        for key in cats:
            group = sorted(by_cat[key], key=lambda r: (value_of(r), r.get("id") or ""))
            lines.append("### «%s»" % key[1])
            for row in group:
                lines.append("    %-5s %s  — %s"
                             % (value_of(row), row.get("canonical_answer") or "?",
                                gist(row.get("clue_text"))))
            lines.append("")

    text = "\n".join(lines).rstrip() + "\n"
    path = os.path.join(ROOT, dest)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    return dest, len(rows), len(by_cat), len(text)


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--lang", choices=("en", "fa"), action="append",
                    help="which board(s); default both")
    args = ap.parse_args()
    langs = args.lang or ["en", "fa"]

    for lang in langs:
        src = os.path.join(ROOT, ARCHIVES[lang][0])
        with open(src, encoding="utf-8") as fh:
            rows = json.load(fh)
        dest, n_rows, n_cats, n_chars = digest(lang, rows)
        print("  %s: %d rows, %d categories -> %s (%d KB)"
              % (lang, n_rows, n_cats, dest, n_chars // 1024))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
