#!/usr/bin/env python3
# 135 Double Jeopardy Categories with Puns in English and Farsi
DOUBLE_135 = [
    # 45 Base Double Categories
    {"en": "1978: A REVOLUTION ODYSSEY", "fa": "۱۳۵۷: ادیسه یک انقلاب", "period": "Islamic Revolution", "theme": "Year of Revolution"},
    {"en": "A MARRIAGE OF INCONVENIENCE", "fa": "وصلت با طعم سیاست", "period": "Pahlavi Era", "theme": "Royal Marriages"},
    {"en": "AIRLINES AND AIR RAIDS", "fa": "آژیر قرمز در آسمان", "period": "Sacred Defense", "theme": "Aerial Warfare"},
    {"en": "APADANA & APARTMENTS", "fa": "ستون‌های آپادانا و سقف‌های امروزی", "period": "Achaemenid & Modern", "theme": "Architecture"},
    {"en": "AYAT-ALL-THAT", "fa": "عمامه‌های پرنفوذ", "period": "All Eras", "theme": "Maraje & Clergy"},
    {"en": "AZERBAIJAN CRISIS: 1946", "fa": "بحران ارس و قوام‌السلطنه", "period": "Cold War", "theme": "Soviet Crisis"},
    {"en": "BARBAD TO THE BONE", "fa": "باربد و زخمه‌های کهن", "period": "Sasanian & Classical", "theme": "Music Masters"},
    {"en": "BAZARGAN'S BLUNT BLADE", "fa": "چاقوی بی‌دسته بازرگان", "period": "Provisional Gov", "theme": "1979 Cabinet"},
    {"en": "CHESS WITH DOOMSDAY MACHINES", "fa": "شطرنج با ماشین قیامت", "period": "Sacred Defense", "theme": "Frontline Literature"},
    {"en": "CROWN JEWELS AND CROWD JEERS", "fa": "برق جواهر، بانگ اعتراض", "period": "Qajar & Pahlavi", "theme": "Treasury"},
    {"en": "DEFENSE OF THE REALM", "fa": "سنگر و سلحشور", "period": "Sacred Defense", "theme": "War Milestones"},
    {"en": "DESERT ONE & DONE", "fa": "پنجه در شن", "period": "Hostage Crisis", "theme": "Operation Eagle Claw"},
    {"en": "FISH LAKE & TANK TRAPS", "fa": "کانال ماهی و باران آهن", "period": "Sacred Defense", "theme": "Operation Karbala-5"},
    {"en": "FROM KARKHEH WITH LOVE", "fa": "از کرخه تا راین", "period": "Sacred Defense", "theme": "Cinema & Literature"},
    {"en": "GHARBZADEGI & GRIEVANCE", "fa": "غرب‌زدگی با جلال و جبروت", "period": "1960s-1970s", "theme": "Intellectuals"},
    {"en": "HAWZA LIFE TREATING YOU?", "fa": "درس خارج و سیاست داخل", "period": "Islamic Era", "theme": "Seminaries of Najaf & Qom"},
    {"en": "JUNGLE GUERRILLAS OF GILAN", "fa": "میرزا کوچک در جنگل مه‌آلود", "period": "WWI & Aftermath", "theme": "Jangal Movement"},
    {"en": "KHALKHALI'S GAVEL DROPS", "fa": "چکش قاضی بر بام مدرسه رفاه", "period": "1979 Revolution", "theme": "Revolutionary Tribunals"},
    {"en": "MINIATURE GOLF NO MINIATURE ART", "fa": "مینیاتورهای بهزاد و قلم‌موهای استاد", "period": "Timurid & Safavid", "theme": "Miniatures"},
    {"en": "MOSSAD-EGH IN THE MIDDLE", "fa": "مصدق در منگنه لاهه", "period": "Pahlavi Era", "theme": "1951-1953 Crisis"},
    {"en": "OPEC AND DOWN", "fa": "اوپک و بشکه‌های طلای سیاه", "period": "Pahlavi Era", "theme": "1973 Oil Shock"},
    {"en": "OPERATION AJAX & CLEANSER", "fa": "آژاکس و کف روی آب", "period": "Pahlavi Era", "theme": "1953 Coup"},
    {"en": "PRAYING MANTIS ON PATROL", "fa": "آخوندک در خلیج فارس", "period": "Sacred Defense", "theme": "1988 Tanker War"},
    {"en": "RADIO TEHRAN CALLING", "fa": "اینجا تهران است، صدای ایران", "period": "Pahlavi & War", "theme": "Broadcasting"},
    {"en": "REVOLUTION OF THE SHAH & PEOPLE", "fa": "انقلاب سفید یا سرخ؟", "period": "Pahlavi Era", "theme": "White Revolution"},
    {"en": "SAVAK TO THE FUTURE", "fa": "سواک و چشم‌های نگران", "period": "Pahlavi Era", "theme": "Security Apparatus"},
    {"en": "SHAH-ME ON YOU", "fa": "شاه‌بازی و بازی‌های دربار", "period": "Pahlavi Era", "theme": "Pahlavi Court"},
    {"en": "SIAHKAL & HYDE", "fa": "سیاهکل و چریک‌های جنگل", "period": "Pahlavi Era", "theme": "Guerrilla Movements"},
    {"en": "TABAS SANDS AND HELICOPTER COMMANDS", "fa": "شن‌های روان، عقاب‌های نگران", "period": "Hostage Crisis", "theme": "Tabas Rescue"},
    {"en": "TAHRIR-IC VOCALS", "fa": "تحریرهای استاد و ربنا", "period": "All Eras", "theme": "Persian Vocals"},
    {"en": "THE ANJOMAN GANG", "fa": "شب‌نامه‌ها و انجمن‌های مخفی", "period": "Constitutional Revolution", "theme": "Secret Societies"},
    {"en": "THE BAKHTIARI MARCH", "fa": "سواران بختیاری در بهارستان", "period": "Constitutional Revolution", "theme": "Tribal Cavalry"},
    {"en": "THE BOMBARDMENT CHRONICLES", "fa": "توپ در زمین مجلس", "period": "Constitutional Revolution", "theme": "Minor Tyranny"},
    {"en": "THE CASPIAN PIPELINE DREAM", "fa": "خط لوله و رؤیای خزر", "period": "Pahlavi & Modern", "theme": "Energy Infrastructure"},
    {"en": "THE GREAT GAME OF THRONES", "fa": "بازی بزرگ میان خرس و شیر", "period": "19th Century", "theme": "Anglo-Russian Rivalry"},
    {"en": "THE IRON COSSACK: REZA SHAH", "fa": "چکمه‌های قزاق", "period": "Pahlavi Era", "theme": "Reza Shah Statehood"},
    {"en": "THE RED AND THE BLACK", "fa": "اتحاد سرخ و سیاه", "period": "Pre-1979", "theme": "Ideological Coalitions"},
    {"en": "THE SEVEN LABORS OF ROSTAM", "fa": "هفت‌خوان رستم دستان", "period": "Shahnameh", "theme": "Epic Feats"},
    {"en": "THE SHAHS SECRET ILLNESS", "fa": "راز سرطان در چمدان شاه", "period": "Late Pahlavi", "theme": "Shah's Health & Exile"},
    {"en": "THE SPY WHO LIKED KEBAB", "fa": "جاسوس سیا با طعم کباب کوبیده", "period": "Cold War", "theme": "Tehran Espionage"},
    {"en": "THE SULTAN OF SOLTANIYEH", "fa": "گنبد فیروزه‌ای سلطانیه", "period": "Ilkhanid Era", "theme": "Ilkhanid Architecture"},
    {"en": "TURKMEN-CHAY TEA PARTY", "fa": "چای قندپهلو در ترکمنچای", "period": "Qajar Era", "theme": "Russo-Persian Wars"},
    {"en": "TWELVE DOLLARS A BARREL", "fa": "دوازده دلار برای هر بشکه نفت", "period": "Pahlavi Era", "theme": "Petrodollars"},
    {"en": "WHAT KHOMEINI ACTUALLY SAID", "fa": "آنچه در نوفل‌لوشاتو گذشت", "period": "1978-1979", "theme": "Khomeini Speeches"},
    {"en": "WOMEN WHO MOVED THE REALM", "fa": "زنانی که تاریخ را چرخاندند", "period": "Qajar to Modern", "theme": "Women Leaders"},

    # 90 New Double Categories (46 to 135)
    {"en": "BEHISTUN'S TRILINGUAL ROCK", "fa": "صخره سه‌زبانه بیستون", "period": "Achaemenid Empire", "theme": "Cuneiform Tablets"},
    {"en": "PASARGADAE GARDEN ARCHITECTURE", "fa": "چهارباغ کوروش در پاسارگاد", "period": "Achaemenid Empire", "theme": "Gardens"},
    {"en": "XERXES CROSSES THE HELLESPONT", "fa": "خشایارشا و پل‌های هلسبونت", "period": "Achaemenid Empire", "theme": "Greco-Persian Wars"},
    {"en": "SUSA'S SHINING CAPITAL", "fa": "کاخ آپادانای شوش و آجر‌های لعاب‌دار", "period": "Achaemenid & Elam", "theme": "Ancient Capitals"},
    {"en": "MITHRIDATES II & SILK COMMERCE", "fa": "مهرداد دوم و معاهده با امپراتور چین", "period": "Parthian Empire", "theme": "Silk Diplomacy"},
    {"en": "SURENA'S ARROW CAMEL TRAINS", "fa": "کاروان شترهای تیرانداز سورنا", "period": "Parthian Empire", "theme": "Tactics"},
    {"en": "PARTHIAN RHYTONS OF NISA", "fa": "ریتون‌های شاخ‌شکل عاج در نسا", "period": "Parthian Empire", "theme": "Sculpture"},
    {"en": "ARDASHIR'S ZOROASTRIAN CODEX", "fa": "اوستای گردآوری‌شده تنسر در عهد اردشیر", "period": "Sasanian Empire", "theme": "Religion & State"},
    {"en": "SHAPUR II'S ARABIAN CRUSADE", "fa": "شاپور ذوالاکتاف و امنیت خلیج فارس", "period": "Sasanian Empire", "theme": "Desert Campaigns"},
    {"en": "KHOSROW PARVIZ & SHIRIN'S MELODY", "fa": "خسرو و شیرین؛ نغمه‌های باربد و نکیسا", "period": "Sasanian Empire", "theme": "Court Romance"},
    {"en": "GUNDESHAPUR'S GREEK PHYSICIANS", "fa": "مهاجرت پزشکان یونانی به گندی‌شاپور", "period": "Sasanian Empire", "theme": "Medical Translation"},
    {"en": "TAQ-E BOSTAN BOAR HUNTS", "fa": "شکارگاه گراز در سنگ‌نگاره‌های طاق بستان", "period": "Sasanian Empire", "theme": "Royal Hunts"},
    {"en": "QADISIYYAH DESERT STORM", "fa": "نبرد قادسیه و فرار رستم فرخزاد", "period": "Sasanian Fall", "theme": "Arab Conquest"},
    {"en": "YAZDEGERD III'S LAST STAND", "fa": "واپسین پناهگاه یزدگرد سوم در آسیاب مرو", "period": "Sasanian Fall", "theme": "Fall of Dynasty"},
    {"en": "SHU'UBIYYA PERSIAN LITERARY PRIDE", "fa": "نهضت شعوبیه و افتخار به فرهنگ ایرانی", "period": "Abbasid Era", "theme": "Cultural Resistance"},
    {"en": "BARMAKID VIZIERS OF HARUN", "fa": "سقوط خاندان برمکی در دربار هارون‌الرشید", "period": "Abbasid Era", "theme": "Persian Viziers"},
    {"en": "TAHIR DHU AL-YAMINAYN'S SWORD", "fa": "طاهر ذوالیمینین و قطع خطبه خلیفه", "period": "Tahirid Dynasty", "theme": "Autonomy"},
    {"en": "YAQUB LAYTH MARCHES ON BAGHDAD", "fa": "لشکرکشی یعقوب لیث تا دروازه دیرالعاقول", "period": "Saffarid Dynasty", "theme": "Saffarid Wars"},
    {"en": "NASR II'S COURT AT BUKHARA", "fa": "دربار ادب‌پرور نصر بن احمد سامانی", "period": "Samanid Dynasty", "theme": "Persian Renaissance"},
    {"en": "AVICENNA'S CANON OF MEDICINE", "fa": "قانون در طب ابن‌سینا در دانشگاه‌های جهان", "period": "Medieval Islamic", "theme": "Medical Science"},
    {"en": "BUYID AZOD AL-DOWLEH'S BAND-E AMIR", "fa": "بند امیر فارس در عصر عضدالدوله دیلمی", "period": "Buyid Dynasty", "theme": "Engineering"},
    {"en": "SULTAN MAHMUD & FERDOWSI'S COINS", "fa": "صلت نقره‌ای سلطان محمود به فردوسی طوسی", "period": "Ghaznavid Empire", "theme": "Shahnameh Patronage"},
    {"en": "AL-BIRUNI'S INDICA CHRONICLES", "fa": "تحقیق ماللهند ابوریحان بیرونی", "period": "Ghaznavid Era", "theme": "Comparative Religion"},
    {"en": "NIZAM AL-MULK'S ASSASSINATION", "fa": "ترور خواجه نظام‌الملک در نهاوند", "period": "Seljuk Empire", "theme": "Fidai Attack"},
    {"en": "OMAR KHAYYAM'S QUADRATIC FORMULA", "fa": "حل معادلات درجه سوم توسط عمر خیام", "period": "Seljuk Empire", "theme": "Mathematics"},
    {"en": "ATTAR OF NISHAPUR'S BIRDS", "fa": "منطق‌الطیر عطار نیشابوری و سیمرغ هفت وادی", "period": "Seljuk & Mongol", "theme": "Mystic Poetry"},
    {"en": "JALAL AL-DIN MANGUBERTI'S INDUS JUMP", "fa": "پرش حماسی جلال‌الدین خوارزمشاه به رود سند", "period": "Khwarazmian Era", "theme": "Resistance to Genghis"},
    {"en": "HULAGU'S DESTRUCTION OF ALAMUT", "fa": "تخریب دژهای اسماعیلیان توسط منجنیق‌های هولاکو", "period": "Ilkhanid Empire", "theme": "Fall of Assassins"},
    {"en": "NASIR AL-DIN TUSI'S ASTROLABES", "fa": "اسطرلاب‌های مسین خواجه نصیر در مراغه", "period": "Ilkhanid Empire", "theme": "Scientific Instruments"},
    {"en": "GHAZAN KHAN'S TAX OVERHAUL", "fa": "اصلاحات مالیاتی و ضرب سکه جدید غازانی", "period": "Ilkhanid Empire", "theme": "Economic Policy"},
    {"en": "TIMUR'S SIEGE OF DAMASCUS", "fa": "ملاقات ابن خلدون و تیمور لنگ در دمشق", "period": "Timurid Empire", "theme": "Timurid Conquests"},
    {"en": "ULUGH BEG'S SEXTANT OF SAMARKAND", "fa": "سکستانت عظیم الغ‌بیگ در رصدخانه سمرقند", "period": "Timurid Empire", "theme": "Astronomy"},
    {"en": "HERAT SCHOOL'S ILLUMINATED SCRIPTS", "fa": "مکتب هرات و شاهکارهای تذهیب و خط", "period": "Timurid Empire", "theme": "Arts"},
    {"en": "SAFAVID TARIQA OF ARDABIL", "fa": "خانقاه شیخ صفی‌الدین اردبیلی و کلاه‌های قزلباش", "period": "Safavid Origins", "theme": "Sufi Order"},
    {"en": "SHAH ISMAIL'S SHI'ISM PROCLAMATION", "fa": "رسمیت مذهب تشیع در مسجد جامع تبریز", "period": "Safavid Empire", "theme": "1501 Declaration"},
    {"en": "BATTLE OF CHALDIRAN MUSKETS", "fa": "توپخانه عثمانی در برابر شمشیرهای قزلباش چالدران", "period": "Safavid Empire", "theme": "1514 War"},
    {"en": "SHAH TAHMASP'S CARPET OF ARDABIL", "fa": "فرش مشهور اردبیل در موزه ویکتوریا و آلبرت", "period": "Safavid Empire", "theme": "Carpets"},
    {"en": "SHAH ABBAS'S GHULAMS CORPS", "fa": "سپاه غلامان خاصه شریفه شاه عباس", "period": "Safavid Empire", "theme": "Military Reforms"},
    {"en": "NAQSH-E JAHAN SQUARE POLO MATCHES", "fa": "چوگان‌بازی شاه عباس در میدان نقش جهان", "period": "Safavid Empire", "theme": "Isfahan Court"},
    {"en": "LOTFOLLAH MOSQUE SANS MINARETS", "fa": "مسجد شیخ لطف‌الله؛ گنبد کرم‌رنگ بدون مناره", "period": "Safavid Empire", "theme": "Sacred Architecture"},
    {"en": "CHARDIN'S TRAVELS IN PERSIA", "fa": "سفرنامه سر ژان شاردن فرانسوی در دربار اصفهان", "period": "Safavid Empire", "theme": "European Chronicles"},
    {"en": "MULLA SADRA'S PRIMACY OF EXISTENCE", "fa": "اصالت وجود و حرکت جوهری ملاصدرا در کهک", "period": "Safavid Empire", "theme": "Metaphysics"},
    {"en": "AFGHAN INVASION AT GULNABAT", "fa": "شکست ارتش صفوی در نبرد گلون‌آباد", "period": "Safavid Fall", "theme": "Battle of 1722"},
    {"en": "NADER'S SACK OF KARNAL", "fa": "نبرد کرنال و تسلیم شدن محمدشاه گورکانی", "period": "Afsharid Empire", "theme": "Invasion of India"},
    {"en": "NADER'S MOGHUL TREASURES", "fa": "غنایم هندوستان؛ تاج‌ها و مرواریدهای نادرشاه", "period": "Afsharid Empire", "theme": "Spoils"},
    {"en": "NADER'S BLINDING OF HIS SON", "fa": "نابینا کردن رضاقلی میرزا و جنون نادرشاه", "period": "Afsharid Empire", "theme": "Tragedy"},
    {"en": "KARIM KHAN REFUSES THE SHAH TITLE", "fa": "رد عنوان شاهنشاه توسط وکیل‌الرعایا کریم‌خان", "period": "Zand Dynasty", "theme": "Zand Humility"},
    {"en": "VAKIL MOSQUE MARBLE PILLARS", "fa": "ستون‌های یکپارچه سنگی مسجد وکیل شیراز", "period": "Zand Dynasty", "theme": "Architecture"},
    {"en": "LOTF-ALI KHAN'S BLINDING IN KERMAN", "fa": "کور کردن مردم کرمان توسط آقامحمدخان قاجار", "period": "Qajar Rise", "theme": "Siege of Kerman 1794"},
    {"en": "FATH-ALI SHAH'S SEVENTY SONS", "fa": "ریش بلند فتحعلی‌شاه و ایل پرتعداد شاهزادگان", "period": "Qajar Dynasty", "theme": "Qajar Court"},
    {"en": "TREATY OF TURKMENCHAY CAPITULATIONS", "fa": "کاپیتولاسیون و مصونیت قضایی اتباع روسیه", "period": "Qajar Dynasty", "theme": "1828 Treaty"},
    {"en": "AMIR KABIR'S VACCINATION CAMPAIGN", "fa": "مبارزه امیرکبیر با آبله و خرافات در تهران", "period": "Qajar Dynasty", "theme": "Public Health"},
    {"en": "FIN BATHHOUSE ASSASSINATION OF AMIR", "fa": "فصد رگ‌های امیرکبیر در حمام فین کاشان", "period": "Qajar Dynasty", "theme": "Martyrdom of Reformer"},
    {"en": "MIRZA AGHA KHAN NURI'S ANGLOPHILIA", "fa": "میرزا آقاخان نوری؛ صدراعظم دست‌نشانده انگلیس", "period": "Qajar Dynasty", "theme": "Pro-British Court"},
    {"en": "BAHAI MASSACRES & QORRAT AL-AYN", "fa": "کشف حجاب طاهره قرةالعین در کنفرانس بدشت", "period": "Qajar Dynasty", "theme": "Religious Dissent"},
    {"en": "TELEGRAPH WIRES IN PERSIA", "fa": "سیم تلگراف هند و اروپا و پدیده بست‌نشینی", "period": "Qajar Dynasty", "theme": "Modern Technology"},
    {"en": "COSSACK BRIGADE INAUGURATION 1879", "fa": "تأسیس دیویزیون قزاق توسط مربیان روسی", "period": "Qajar Dynasty", "theme": "Cossack Brigade"},
    {"en": "TALBOT CONCESSION TELEGRAM FROM SAMARRA", "fa": "تلگراف تاریخی سامرا و لغو قرارداد توتون و تنباکو", "period": "Qajar Dynasty", "theme": "Mirza Shirazi"},
    {"en": "SHAH'S PHOTO ARCHIVES AT GOLESTAN", "fa": "آلبوم‌خانه کاخ گلستان و عکس‌های ناصرالدین‌شاه", "period": "Qajar Dynasty", "theme": "Early Photography"},
    {"en": "MIRZA REZA'S TRIAL DOCUMENTS", "fa": "استنطاق میرزا رضای کرمانی پیش از اعدام", "period": "Qajar Dynasty", "theme": "Interrogation Records"},
    {"en": "MOZAFFAR AL-DIN'S EUROPEAN SPENDING", "fa": "وام‌های سنگین مظفرالدین‌شاه برای سفرهای فرنگ", "period": "Qajar Dynasty", "theme": "State Debt"},
    {"en": "BRITISH LEGATION GARDEN TENTS 1906", "fa": "چادرهای اصناف و تجار در باغ سفارت بریتانیا", "period": "Constitutional Revolution", "theme": "Bast of 1906"},
    {"en": "FIRST NATIONAL ASSEMBLY SESSIONS", "fa": "افتتاح مجلس اول در بهارستان با نطق شاه", "period": "Constitutional Revolution", "theme": "Majles 1906"},
    {"en": "ANGLO-RUSSIAN ENTENTE OF 1907", "fa": "قرارداد ۱۹۰۷ سن‌پترزبورگ و تقسیم ایران", "period": "Constitutional Revolution", "theme": "Partition Spheres"},
    {"en": "SUR-E ESRAFIL DISPATCHES", "fa": "چرند و پرند دهخدا در روزنامه صوراسرافیل", "period": "Constitutional Revolution", "theme": "Satire & Journalism"},
    {"en": "MIRZA JAHANGIR KHAN'S STRANGULATION", "fa": "خفه کردن میرزا جهانگیرخان در باغ‌شاه طهران", "period": "Constitutional Revolution", "theme": "Martyrs of Liberty"},
    {"en": "SATTAR KHAN'S SEVEN COLORED FLAGS", "fa": "سخنان حماسی ستارخان: هفت دولت زیر پرچم ایران", "period": "Constitutional Revolution", "theme": "Tabriz Resistance"},
    {"en": "BAKHTIARI TRIBES STORM TEHRAN", "fa": "سردار اسعد بختیاری و ورود مجاهدین به پایتخت", "period": "Constitutional Revolution", "theme": "Fall of Mohammad Ali Shah"},
    {"en": "MOHAMMAD ALI SHAH'S RUSSIAN ASYLUM", "fa": "پناهندگی محمدعلی‌شاه مخلوع به سفارت روسیه", "period": "Constitutional Revolution", "theme": "Deposed Tyrant"},
    {"en": "MORGAN SHUSTER'S TREASURY GENDAREMERIE", "fa": "ژاندارمری خزانه‌داری مورگان شوستر آمریکایی", "period": "Constitutional Revolution", "theme": "Treasury Police"},
    {"en": "RUSSIAN ULTIMATUM OF DECEMBER 1911", "fa": "اولتیماتوم روسیه تزاری و انحلال اجباری مجلس دوم", "period": "Constitutional Revolution", "theme": "Majles Dissolution"},
    {"en": "SWEDISH GENDARMERIE OFFICERS IN PERSIA", "fa": "افسران سوئدی و تأسیس ژاندارمری دولتی ایران", "period": "WWI Era", "theme": "Swedish Advisors"},
    {"en": "PERSIAN COSSACKS AT QAZVIN", "fa": "اردوی قزاق‌های قزوین به فرماندهی رضاخان میرپنج", "period": "1921 Coup", "theme": "Coup Logistics"},
    {"en": "EDMUND IRONSIDE'S PERMISSION", "fa": "ژنرال آیرونساید و چراغ سبز به رضاخان سردار سپه", "period": "1921 Coup", "theme": "British Role"},
    {"en": "REZA KHAN BECOMES PRIME MINISTER 1923", "fa": "نخست‌وزیری سردار سپه و خروج احمدشاه از کشور", "period": "Pahlavi Rise", "theme": "Premiership"},
    {"en": "CONSTITUENT ASSEMBLY VOTES PAHLAVI 1925", "fa": "مجلس مؤسسان و اعلام انقراض سلسله قاجار", "period": "Pahlavi Rise", "theme": "End of Qajars"},
    {"en": "DAVAR'S MODERN JUDICIARY REFORMS", "fa": "علی‌اکبر داور و تأسیس دادگستری نوین ایران", "period": "Pahlavi Era", "theme": "Legal Reforms"},
    {"en": "VERESK BRIDGE'S CHUCK TEST", "fa": "ایستادن سرمهندس بر زیر پل ورسک هنگام عبور قطار", "period": "Pahlavi Era", "theme": "Bridge Engineering"},
    {"en": "TEHRAN RADIO FIRST TRANSMISSION 1940", "fa": "نخستین فرستنده رادیو تهران در میدان توپخانه", "period": "Pahlavi Era", "theme": "Radio Launch"},
    {"en": "REZA SHAH'S EXILE TO MAURITIUS", "fa": "کشتی باندرا و تبعید رضاشاه به جزیره موریس", "period": "WWII Era", "theme": "Exile Journey"},
    {"en": "MOHAMMAD REZA SWORN IN 1941", "fa": "سوگند محمدرضا پهلوی ۲۱ ساله در مجلس شورای ملی", "period": "WWII Era", "theme": "New Sovereign"},
    {"en": "TUDEH PARTY FOUNDING BY 53 MARXISTS", "fa": "تأسیس حزب توده توسط بازماندگان گروه ۵۳ نفر", "period": "WWII Era", "theme": "Leftist Organizing"},
    {"en": "SOVIET OIL CONCESSION OF 1946", "fa": "قرارداد قوام-سادچیکف و نفت شمال که هرگز اجرا نشد", "period": "Post-War Era", "theme": "Cold War Treaty"},
    {"en": "AZERBAIJAN RECONQUEST BY IMPERIAL ARMY", "fa": "ورود ارتش ایران به تبریز و پایان غائله پیشه‌وری", "period": "Post-War Era", "theme": "Reconquest 1946"},
    {"en": "MOSSADEGH IN THE HAGUE", "fa": "دفاعیه حقوقی دکتر مصدق در دادگاه بین‌المللی لاهه", "period": "Oil Era", "theme": "Hague Defense"},
    {"en": "30 TIR MARTYRS' CEMETERY", "fa": "شهدای ۳۰ تیر ۱۳۳۱ در قبرستان ابن‌بابویه", "period": "Oil Era", "theme": "Popular Martyrs"},
    {"en": "RADIO TEHRAN SEIZED AUGUST 19", "fa": "تصرف رادیو تهران توسط کودتاچیان در ۲۸ مرداد", "period": "1953 Coup", "theme": "Coup Radio Broadcast"},
    {"en": "TRIAL OF MOSSADEGH AT SULTANABAD", "fa": "محاکمه مصدق در دادگاه نظامی سلطنت‌آباد", "period": "Post-1953", "theme": "Military Trial"},
    {"en": "EXECUTION OF HOSSEIN FATEMI", "fa": "تیرباران دکتر حسین فاطمی در سحرگاه آبان ۱۳۳۳", "period": "Post-1953", "theme": "Execution of Minister"},
    {"en": "1954 OIL CONSORTIUM BREAKDOWN", "fa": "قرارداد کنسرسیوم علی امینی و غول‌های نفتی غرب", "period": "Post-1953", "theme": "Oil Consortium"}
]
