#!/usr/bin/env python3
# 75 Final Jeopardy Categories with Puns in English and Farsi
FINAL_75 = [
    # 25 Base Final Categories
    {"en": "AIR FRANCE TO TEHRAN", "fa": "پرواز انقلاب با ایرفرانس", "period": "1979 Revolution", "theme": "Khomeini Return"},
    {"en": "BULLET AT THE BAST", "fa": "شلیک در بستِ حرم", "period": "Qajar Era", "theme": "Assassination of Shah"},
    {"en": "CYRUS ON ROLLS", "fa": "کوروش روی خط استوانه", "period": "Achaemenid Empire", "theme": "Cyrus Cylinder"},
    {"en": "DEHKHODA'S DEAD CANDLE", "fa": "یاد آر ز شمع مرده، یاد آر", "period": "Constitutional Revolution", "theme": "Dehkhoda Elegy"},
    {"en": "EXACTLY MIDNIGHT", "fa": "دقیقاً نیمه‌شب: رمز بی‌بی‌سی", "period": "1953 Coup", "theme": "BBC Radio Code"},
    {"en": "FATEMI'S LAST STAND", "fa": "فاطمی و آتش ۲۸ مرداد", "period": "Post-1953", "theme": "Fatemi Execution"},
    {"en": "FEREYDUN'S OX-MACE", "fa": "گرز گاوسار فریدون", "period": "Shahnameh", "theme": "Mythic Sovereignty"},
    {"en": "GOLNAR ON CELLULOID", "fa": "دختر لُر در سینما مایاک", "period": "Pahlavi Era", "theme": "First Sound Film"},
    {"en": "JOHANNESBURG BLUES", "fa": "غروب رضاشاه در ژوهانسبورگ", "period": "WWII Era", "theme": "Reza Shah Exile"},
    {"en": "KHORRAMSHAHR UNBOUND", "fa": "خرمشهر؛ شهری که خرم شد", "period": "Sacred Defense", "theme": "Liberation of Khorramshahr"},
    {"en": "LIAKHOV'S CANNONS", "fa": "توپ‌های لیاخوف بر بهارستان", "period": "Constitutional Revolution", "theme": "Bombardment of Majles"},
    {"en": "MOZAFFAR'S DYING STAMP", "fa": "امضای واپسین مظفرالدین‌شاه", "period": "Constitutional Revolution", "theme": "1906 Fundamental Law"},
    {"en": "SEA OF LIGHT DIAMOND", "fa": "دریای نور در گنجینه جواهرات", "period": "Afsharid to Pahlavi", "theme": "Daria-i-Noor"},
    {"en": "SHUSTER'S INDICTMENT", "fa": "شوستر و اختناق ایران", "period": "Constitutional Revolution", "theme": "The Strangling of Persia"},
    {"en": "THALWEG BLUES", "fa": "خط تالوگ در اروندرود", "period": "Pahlavi Era", "theme": "1975 Algiers Accord"},
    {"en": "THE FORGOTTEN CAPITAL", "fa": "قزوین؛ پایتخت فراموش‌شده صفوی", "period": "Safavid Empire", "theme": "Qazvin Capital"},
    {"en": "THE GALA OF PEACOCKS", "fa": "طاووس‌های تخت طاووس", "period": "Late Pahlavi", "theme": "1971 Gala Attire"},
    {"en": "THE GOLDEN VEST OF REZA SHAH", "fa": "جلیقه زرین و تاج پهلوی", "period": "Pahlavi Era", "theme": "Reza Khan Cossack Vest"},
    {"en": "THE JAMEH RESISTANCE", "fa": "مقاومت در مسجد جامع خرمشهر", "period": "Sacred Defense", "theme": "Khorramshahr Mosque"},
    {"en": "THE LION OF AZERBAIJAN", "fa": "شیر آذربایجان بر دوش ستارخان", "period": "Constitutional Revolution", "theme": "Sattar Khan Title"},
    {"en": "THE POISONED CHALICE LETTER", "fa": "جرعه آخر از جام زهر", "period": "Sacred Defense", "theme": "Resolution 598"},
    {"en": "THE SHAH'S SIX POINTS", "fa": "شش اصل انقلاب سفید", "period": "Pahlavi Era", "theme": "White Revolution 1963"},
    {"en": "TUS MARBLE CONGRESS", "fa": "کنگره هزاره فردوسی در طوس", "period": "Pahlavi Era", "theme": "Ferdowsi Mausoleum"},
    {"en": "VAULT OF CTESIPHON", "fa": "تاق و جفت کسری در تیسفون", "period": "Sasanian Empire", "theme": "Taq-e Kasra"},
    {"en": "ZAND OF HOPE & GLORY", "fa": "وکیل‌الرعایا در شیراز پر گل", "period": "Zand Dynasty", "theme": "Karim Khan Vakil"},

    # 50 New Final Categories (26 to 75)
    {"en": "CHOGHA ZANBIL ZIGGURAT", "fa": "زیگورات چغازنبیل در هفت‌تپه", "period": "Elamite Empire", "theme": "Elamite Temple"},
    {"en": "CYAXARES CRUSHES NINEVEH", "fa": "هووخشتره مادی و سقوط نینوا", "period": "Median Empire", "theme": "Assyrian Fall"},
    {"en": "CAMBYSES IN EGYPT", "fa": "کمبوجیه و فتح مصر باستان", "period": "Achaemenid Empire", "theme": "Egyptian Campaign"},
    {"en": "BEHISTUN SMITING GAUMATA", "fa": "داریوش و لگدمال کردن گئومات غاصب", "period": "Achaemenid Empire", "theme": "Accession"},
    {"en": "PERSEPOLIS GATE OF ALL NATIONS", "fa": "دروازه ملل با گاوهای بالدار خشایارشا", "period": "Achaemenid Empire", "theme": "Apadana"},
    {"en": "BATTLE OF GUAGAMELA DARIUS III", "fa": "داریوش سوم در نبرد سرنوشت گوگمل", "period": "Achaemenid Empire", "theme": "Fall of Empire"},
    {"en": "MITHRIDATES I COINAGE", "fa": "سکه نقره مهرداد یکم با لقب فیل‌هلن", "period": "Parthian Empire", "theme": "Numismatics"},
    {"en": "ORODES II & CRASSUS GOLD", "fa": "ریختن طلای مذاب در گلوی کراسوس", "period": "Parthian Empire", "theme": "Carrhae Legend"},
    {"en": "ARTABANUS IV AT HORMISDGAN", "fa": "نبرد هرمزدگان و سقوط اشکانیان", "period": "Parthian Fall", "theme": "Rise of Sasan"},
    {"en": "VALERIAN SHAPUR ROCK CARVING", "fa": "زنجیر اسارت والریانوس در نقش رستم", "period": "Sasanian Empire", "theme": "Bishapur"},
    {"en": "KERDIR ZOROASTRIAN HIGH PRIEST", "fa": "موبد موبدان کرتیر و کتیبه‌های کعبه زرتشت", "period": "Sasanian Empire", "theme": "Clerical Hegemony"},
    {"en": "MANI THE PROPHET OF LIGHT", "fa": "مانی نقاش و ارژنگ نور و ظلمت", "period": "Sasanian Empire", "theme": "Manichaeism"},
    {"en": "BARZWAYH BRINGS PANCHATANTRA", "fa": "برزویه طبیب و آوردن کلیله و دمنه از هند", "period": "Sasanian Empire", "theme": "Translation"},
    {"en": "BOZORGMEHR THE GRAND VIZIER", "fa": "بزرگمهر بختگان و رمزگشایی تخته‌نرد و شطرنج", "period": "Sasanian Empire", "theme": "Court Sages"},
    {"en": "ROSTAM FARROKHZAD'S LETTER", "fa": "نامه رستم فرخزاد به برادرش در شاهنامه", "period": "Sasanian Fall", "theme": "Ferdowsi Epics"},
    {"en": "SINBAD THE ZOROASTRIAN REBEL", "fa": "قیام سنباد نیشابوری به خونخواهی ابومسلم", "period": "Early Islamic", "theme": "Persian Uprisings"},
    {"en": "BABAK KHORRAMDIN AT BAZZ", "fa": "بابک خرمدین و ۲۰ سال پایداری در قلعه بذ", "period": "Early Islamic", "theme": "Khorramite Revolt"},
    {"en": "MAZIYAR'S TABARISTAN RESISTANCE", "fa": "مازیار قارنوندی در کوهستان‌های طبرستان", "period": "Early Islamic", "theme": "Caspian Independence"},
    {"en": "SHAHNAMEH MANUSCRIPT OF FLORENCE", "fa": "دست‌نویس فلورانس شاهنامه فردوسی (۱۲۱۷ میلادی)", "period": "Medieval", "theme": "Oldest Manuscript"},
    {"en": "TARIKH-E BEYHAQI DISPATCHES", "fa": "تاریخ بیهقی؛ شاهکار نثر فارسی و دار زدن حسنک وزیر", "period": "Ghaznavid Era", "theme": "Historical Prose"},
    {"en": "HASAN-I SABBAH'S CHERISHED GARDEN", "fa": "فداییان حشاشین و رمز و راز حسن صباح", "period": "Ismaili Era", "theme": "Alamut Legends"},
    {"en": "SAADI'S GOLESTAN PREFACE", "fa": "دیباچه گلستان سعدی شیرازی در دارالسلام شیراز", "period": "Medieval", "theme": "Masterpiece of Prose"},
    {"en": "HAFIZ & TAMERLANE ENCOUNTER", "fa": "دیدار تیمور لنگ و حافظ: به خال هندویش بخشم", "period": "Timurid Era", "theme": "Literary Legend"},
    {"en": "TAHMASP SHAHNAMEH 258 MINIATURES", "fa": "شاهنامه شاه‌طهماسب؛ نگین هنر کتاب‌آرایی جهان", "period": "Safavid Empire", "theme": "Royal Manuscript"},
    {"en": "ALLAHVERDI KHAN'S BRIDGE DECREE", "fa": "الله‌وردی‌خان گرجی و ساخت سی‌وسه‌پل اصفهان", "period": "Safavid Empire", "theme": "Safavid Generals"},
    {"en": "IMAM QULI KHAN'S PERSIAN GULF TRIUMPH", "fa": "سردار امام‌قلی‌خان و آزادسازی بحرین و هرمز", "period": "Safavid Empire", "theme": "Naval Victory"},
    {"en": "SHAH SULTAN HUSAYN TASTES SHERBET", "fa": "شربت زعفران شاه سلطان حسین در محاصره اصفهان", "period": "Safavid Fall", "theme": "Tragic Decadence"},
    {"en": "NADER SHAH CORONATION MUGHOUL CROWN", "fa": "شورای دشت مغان ۱۷۳۶ و پادشاهی نادرشاه", "period": "Afsharid Empire", "theme": "Mughan Plain"},
    {"en": "VAKIL AL-RO'AYA PIR SHIRAZ", "fa": "سنگ مزار کریم‌خان زند که آقامحمدخان به کاخ برد", "period": "Zand to Qajar", "theme": "Royal Bones"},
    {"en": "AGHA MOHAMMAD KHAN'S SHUSHA MURDER", "fa": "قتل آقامحمدخان قاجار در قلعه شوشی قره‌باغ", "period": "Qajar Era", "theme": "Assassination 1797"},
    {"en": "ASLANDOZ RUSSIAN CANNON VOLLEY", "fa": "شکست غم‌انگیز عباس‌میرزا در نبرد اصلاندوز", "period": "Qajar Era", "theme": "Russo-Persian War"},
    {"en": "FIN BATHHOUSE COLD MARBLE", "fa": "سنگ مرمر خونین حمام فین در شهادت امیرکبیر", "period": "Qajar Era", "theme": "Amir Kabir"},
    {"en": "DAR AL-FONUN FIRST GRADUATING CLASS", "fa": "نخستین دوره فارغ‌التحصیلان اتریشی دارالفنون", "period": "Qajar Era", "theme": "Polytechnic"},
    {"en": "NASIR AL-DIN SHAH'S ASSASSIN PISTOL", "fa": "تپانچه پنج‌تیر میرزا رضای کرمانی در ۱۸۹۶", "period": "Qajar Era", "theme": "Regicide"},
    {"en": "TOBACCO PROTEST SAMARRA FATWA", "fa": "دست‌خط میرزای شیرازی در تحریم مطلق توتون و تنباکو", "period": "Qajar Era", "theme": "Religious Decree"},
    {"en": "1906 CONSTITUTIONAL DECREE INK", "fa": "مرکب امضای مشروطیت توسط مظفرالدین‌شاه بیمار", "period": "Constitutional Revolution", "theme": "Foundational Decree"},
    {"en": "BAHAR'S POETIC DAMAVAND ODE", "fa": "قصیده دماوندیه ملک‌الشعرای بهار: ای دیو سپید پای در بند", "period": "Modern Era", "theme": "Constitutional Poetry"},
    {"en": "SATTAR KHAN GRAVE AT SHAH ABDOL-AZIM", "fa": "آرامگاه غریبانه سردار ملی ستارخان در باغ طوطی", "period": "Constitutional Revolution", "theme": "Sattar Khan Resting Place"},
    {"en": "LIAKHOV'S FLIGHT AFTER TEHRAN CONQUEST", "fa": "فرار کلنل لیاخوف پس از تسخیر پایتخت توسط مشروطه‌خواهان", "period": "Constitutional Revolution", "theme": "Cossack Defeat"},
    {"en": "COLONEL PESYAN AIR ACCIDENT", "fa": "کلنل پسیان؛ نخستین خلبان ایرانی و حماسه قوچان", "period": "Interwar Era", "theme": "First Aviator"},
    {"en": "VERESK BRIDGE CONQUERING ALBORZ", "fa": "پل ورسک در دره سوادکوه مازندران با دهانه ۶۶ متری", "period": "Pahlavi Era", "theme": "Bridge Landmark"},
    {"en": "ANDRE GODARD'S NATIONAL MUSEUM", "fa": "موزه ایران باستان با الهام از طاق کسری ساسانی", "period": "Pahlavi Era", "theme": "National Museum"},
    {"en": "1943 TEHRAN CONFERENCE STALIN BIRTHDAY", "fa": "کیک تولد ۶۹ سالگی چرچیل در سفارت بریتانیا در تهران", "period": "WWII Era", "theme": "Tehran Conference 1943"},
    {"en": "PISHEVARI'S FLIGHT TO BAKU", "fa": "فرار جعفر پیشه‌وری به باکو و پایان غائله آذربایجان", "period": "Post-War Era", "theme": "Azerbaijan 1946"},
    {"en": "MOSSADEGH TIME MAN OF THE YEAR 1951", "fa": "عکس دکتر مصدق به عنوان مرد سال مجله تایم ۱۹۵۱", "period": "Oil Era", "theme": "Global Acclaim"},
    {"en": "AHMADABAD RESIDENCE CONFINEMENT", "fa": "تبعیدگاه و آرامگاه دکتر مصدق در قلعه احمدآباد", "period": "Post-1953", "theme": "Ahmadabad Prison"},
    {"en": "1971 PERSEPOLIS TENT CITY", "fa": "شهرک خیمه‌ای ۵۰ خیمه فرانسوی در جشن ۲۵۰۰ ساله تخت جمشید", "period": "Late Pahlavi", "theme": "Persepolis Tents"},
    {"en": "OPERATION BEIT OL-MOQADDAS CODE", "fa": "رمز یا علی ابن ابی‌طالب در آزادسازی خرمشهر", "period": "Sacred Defense", "theme": "Khorramshahr Liberation"},
    {"en": "RESOLUTION 598 DRINKING POISON", "fa": "نامه تاریخی امام: جام زهر را سر می‌کشم", "period": "Sacred Defense", "theme": "UN Resolution 598"},
    {"en": "RAVAYAT-E FATH FINAL BROADCAST", "fa": "شهادت سید مرتضی آوینی در قتلگاه فکه با مین والمر", "period": "Sacred Defense", "theme": "Martyr of the Pen"}
]
