#!/usr/bin/env python3
# 150 Single Jeopardy Categories with Puns in English and Farsi
SINGLE_150 = [
    # 1 to 50
    {"en": "WE DON'T COTTON TO CONCESSIONS", "fa": "حراج قرن قاجار", "period": "Qajar", "theme": "Diplomatic"},
    {"en": "A MASH-RUTEH MADE IN HEAVEN", "fa": "مشروطه به شرط چاقو", "period": "Constitutional Revolution", "theme": "Political"},
    {"en": "OIL, OBVIOUSLY", "fa": "نفت، معلومه دیگه!", "period": "Pahlavi", "theme": "Economic"},
    {"en": "LIGHTS ON LALEZAR", "fa": "لاله‌زار؛ برادوی طهران", "period": "Qajar & Pahlavi", "theme": "Arts & Cinema"},
    {"en": "A ROLLS-ROYCE FOR REZA", "fa": "رولزرویس و پیکان سواری", "period": "Pahlavi", "theme": "Infrastructure"},
    {"en": "ABAPLAN GONE WRONG", "fa": "نقشه بر آب در آبادان", "period": "Pahlavi", "theme": "Oil & Crisis"},
    {"en": "ALL ABOARD THE VERESK EXPRESS", "fa": "ورسک و سوت قطار پیروزی", "period": "Pahlavi", "theme": "Infrastructure"},
    {"en": "AVICENNA & THE BRAINIACS", "fa": "بوعلی‌بازی و نبوغ ایرانی", "period": "Medieval Islamic", "theme": "Sciences"},
    {"en": "BAZAAR-O WORLD", "fa": "حجره‌های معترض", "period": "Qajar", "theme": "Economic & Social"},
    {"en": "CALLIGRAPHY & INKWELLS", "fa": "خط خوش و دوات پردردسر", "period": "Islamic Eras", "theme": "Arts"},
    {"en": "CARPET DIEM", "fa": "دم را با دارِ قالی غنیمت شمر", "period": "Safavid to Modern", "theme": "Traditional Crafts"},
    {"en": "COWS, CHERRIES & CELLULOID", "fa": "از گاو تا طعم گیلاس", "period": "Modern Iran", "theme": "Cinema"},
    {"en": "DAMAVAND-ING RESPECT", "fa": "دیو سپید پای در بند", "period": "All Eras", "theme": "Geography"},
    {"en": "DAR AL-FUN-UN & GAMES", "fa": "دارالفنون و بازی‌های روزگار", "period": "Qajar", "theme": "Education"},
    {"en": "DEAR DIARY: THE SHAH SPEAKS", "fa": "علم غیب ندارد!", "period": "Pahlavi", "theme": "Court Life"},
    {"en": "DIRECTED BY KIAROSTAMI & CO.", "fa": "کلوزآپِ سینمای ایران", "period": "Post-1960s", "theme": "Cinema"},
    {"en": "FERDOWSI'S RHYME TIME", "fa": "سی سال رنج در شاهنامه", "period": "Medieval Islamic", "theme": "Literature"},
    {"en": "FROM VILLAGE TO VALIASR", "fa": "از طهران تا ولیعصر", "period": "Qajar & Pahlavi", "theme": "Urban History"},
    {"en": "GULF OF PERSIA, NOT DISCORD", "fa": "خلیج همیشه فارس", "period": "All Eras", "theme": "Maritime & Ports"},
    {"en": "HAFIZ THE BEATLES OF SHIRAZ", "fa": "شاخه نبات در فال حافظ", "period": "Medieval Islamic", "theme": "Poetry"},
    {"en": "HORSING AROUND IN NISA", "fa": "اسب‌های نیسا و کمانداران پارتی", "period": "Parthian Empire", "theme": "Antiquity"},
    {"en": "ISFAHAN-TASTIC SAFFAVIDS", "fa": "اصفهان و یک‌چهارمِ دیگرِ جهان", "period": "Safavid Empire", "theme": "Architecture & Power"},
    {"en": "IT'S NIMA OR NEVER", "fa": "ری‌را و شب‌های نیما", "period": "20th Century", "theme": "Modern Poetry"},
    {"en": "JUST FOR THE DASTGAH OF IT", "fa": "دستگاهِ کوک، آوازِ ناکوک", "period": "All Eras", "theme": "Classical Music"},
    {"en": "KHORASAN-WICH", "fa": "زعفران و فیروزه خراسان", "period": "All Eras", "theme": "Regional Culture"},
    {"en": "KINGS OF THE MEDES & BOUNDS", "fa": "پادشاهان ماد در هگمتانه", "period": "Median Empire", "theme": "Ancient History"},
    {"en": "LADIES OF THE CONSTITUTION", "fa": "زنان پیشگام مشروطه", "period": "Constitutional Revolution", "theme": "Women's History"},
    {"en": "LUT'S GET PHYSICAL", "fa": "داغ‌ترین نقطه در کویر لوت", "period": "All Eras", "theme": "Deserts & Geography"},
    {"en": "MULLA SADRA'S SOUL FOOD", "fa": "حکمت روی حرارت ملایم", "period": "Safavid Empire", "theme": "Philosophy"},
    {"en": "NADER SHAH'S SWORDPLAY", "fa": "شمشیر تیز نادر در دهلی", "period": "Afsharid Empire", "theme": "Conquests"},
    {"en": "NOT IN MY BACK-YAZD", "fa": "بادگیرهای بی‌باد یزد", "period": "All Eras", "theme": "Desert Architecture"},
    {"en": "ONCE UPON A JAMALZADEH", "fa": "یکی بود، یکی جمال‌زاده بود", "period": "20th Century", "theme": "Modern Prose"},
    {"en": "PARTY LIKE IT'S 539 BC", "fa": "مهمانی ۲۵۰۰ سال قبل", "period": "Pahlavi & Antiquity", "theme": "Imperial Celebrations"},
    {"en": "PERSIAN FLIGHTS OF FANCY", "fa": "هما و بال‌های سیمرغ", "period": "Pahlavi & Modern", "theme": "Aviation"},
    {"en": "POETS IN EXILE", "fa": "شعر در غربت", "period": "Contemporary", "theme": "Diaspora Literature"},
    {"en": "QOM WHAT MAY", "fa": "قم؛ هر چه باداباد", "period": "Safavid to Modern", "theme": "Shrines & Pilgrimage"},
    {"en": "ROSTAM'S SEVEN HABITS", "fa": "هفت‌خوان و یک رستم", "period": "Mythic & Epic", "theme": "Shahnameh"},
    {"en": "RUMI WITH A VIEW", "fa": "شمس و مولانا در پرواز", "period": "Medieval", "theme": "Sufism"},
    {"en": "SATTAR WARS: TABRIZ STRIKES BACK", "fa": "جنگ ستار: تبریز وارد می‌شود", "period": "Constitutional Revolution", "theme": "Resistance"},
    {"en": "SEALED WITH A DISS", "fa": "نامه‌های تند و مهرهای درباری", "period": "Qajar", "theme": "Royal Decrees"},
    {"en": "SHAH-PING FOR ANTIQUES", "fa": "عتیقه‌خران در بازار تهران", "period": "Qajar & Pahlavi", "theme": "Jewels & Relics"},
    {"en": "SMOKE 'EM IF YOU'VE GOT 'EM", "fa": "دود از قلیان شاه درآمد", "period": "Qajar", "theme": "Tobacco Protest"},
    {"en": "STARS OVER MARAGHEH", "fa": "ستاره‌بازی در مراغه", "period": "Ilkhanid & Timurid", "theme": "Astronomy & Renaissance"},
    {"en": "TAHDIG YOUR OWN GRAVE", "fa": "ته‌دیگِ تهِ خط", "period": "All Eras", "theme": "Cuisine"},
    {"en": "TAKING A PARTHIAN SHOT", "fa": "تیر خلاص پارتی", "period": "Parthian Empire", "theme": "Military Tactics"},
    {"en": "TALES FROM THE CASPIAN SHORE", "fa": "ماهی خاویار و چای لاهیجان", "period": "All Eras", "theme": "Northern Provinces"},
    {"en": "THE 300 & THEN SOME", "fa": "۳۰۰ و خرده‌ای", "period": "Achaemenid Empire", "theme": "Ancient Warfare"},
    {"en": "THE BREAD & BUTTER OF POLITICS", "fa": "بلوا بر سر نان جو", "period": "Qajar to WWII", "theme": "Urban Riots"},
    {"en": "THE BRIDGE OF VICTORY ROAD", "fa": "پل پیروزی یا پل هوایی؟", "period": "WWII", "theme": "Allied Occupation"},
    {"en": "WE'VE GOT ELAM-ENTARY EVIDENCE", "fa": "زیگورات چغازنبیل و رازهای ایلام", "period": "Elamite Empire", "theme": "Archaeology"},

    # 51 to 100
    {"en": "CYRUS THE GREAT & SMALL", "fa": "کوروش از کوچک تا بزرگ", "period": "Achaemenid Empire", "theme": "Founding of Empire"},
    {"en": "PASARGADAE-N VARIETY", "fa": "پاسارگاد و دشت مرغاب", "period": "Achaemenid Empire", "theme": "Monuments"},
    {"en": "DARIUS THE STAMP COLLECTOR", "fa": "داریوش و مهرهای شاهنشاهی", "period": "Achaemenid Empire", "theme": "Imperial Administration"},
    {"en": "BEHISTUN INSCRIPTIONS & PRESCRIPTIONS", "fa": "بیستون و خط میخی روی صخره", "period": "Achaemenid Empire", "theme": "Epigraphy"},
    {"en": "PERSEPOLIS RISING FROM ASHES", "fa": "تخت جمشید بر بال‌های عقاب", "period": "Achaemenid Empire", "theme": "Architecture"},
    {"en": "IMMORTAL COMBAT", "fa": "سپاه جاویدان در میدان نبرد", "period": "Achaemenid Empire", "theme": "Military"},
    {"en": "ROYAL ROADS & POTHOLES", "fa": "راه شاهی از شوش تا سارد", "period": "Achaemenid Empire", "theme": "Logistics & Couriers"},
    {"en": "SATRAPS & SATELLITES", "fa": "ساتراپ‌ها و والیان ولایات", "period": "Achaemenid Empire", "theme": "Governance"},
    {"en": "ALEXANDER'S ASHES", "fa": "اسکندر و خاکستر پاسارگاد", "period": "Hellenistic Era", "theme": "Conquest & Aftermath"},
    {"en": "SELEUCID SLEEPWALKERS", "fa": "سلوکیان در خواب غفلت", "period": "Seleucid Era", "theme": "Hellenistic Rule"},
    {"en": "MITHRIDATES THE GREAT DEFENDER", "fa": "مهرداد کبیر و رستاخیز پارت", "period": "Parthian Empire", "theme": "Expansion"},
    {"en": "CARRHAE-FUL WHAT YOU WISH FOR", "fa": "کاره؛ فاجعه کراسوس رومی", "period": "Parthian Empire", "theme": "Crassus & Surena"},
    {"en": "SILK ROAD RACERS", "fa": "جاده ابریشم و کاروان‌های زرین", "period": "Parthian to Safavid", "theme": "Trade & Commerce"},
    {"en": "ARDASHIR'S CROWN JEWELS", "fa": "اردشیر بابکان و تاج ساسانی", "period": "Sasanian Empire", "theme": "Founding of Sasanian State"},
    {"en": "SHAPUR TAKES A ROMAN CAPTIVE", "fa": "شاپور یکم و زانوزدن والریانوس", "period": "Sasanian Empire", "theme": "Roman Wars"},
    {"en": "NAQSH-E ROSTAM ROCK OPERA", "fa": "نقش رستم روی سنگ خارا", "period": "Achaemenid & Sasanian", "theme": "Rock Reliefs"},
    {"en": "GUNDESHAPUR ACADEMIC BLUES", "fa": "جندی‌شاپور؛ مهد پزشکان و حکما", "period": "Sasanian Empire", "theme": "Medicine & Academy"},
    {"en": "KHOSROW ANUSHIRVAN'S JUST DESSERTS", "fa": "انوشیروان عادل و زنجیر دادگری", "period": "Sasanian Empire", "theme": "Reforms & Justice"},
    {"en": "MAZDAK'S RED SHIRTS", "fa": "مزدک و تقسیم مساوی گندم", "period": "Sasanian Empire", "theme": "Social Revolts"},
    {"en": "CTESIPHON UNDER SEIGE", "fa": "تیسفون و فتح مدائن", "period": "Sasanian Empire", "theme": "Fall of Empire"},
    {"en": "TAHIRIDS OF NISHAPUR", "fa": "طاهریان نیشابور و نخستین امارت", "period": "Early Islamic", "theme": "Autonomy"},
    {"en": "YAQUB LAYTH'S COPPER POTS", "fa": "یعقوب لیث صفاری و نان و پیاز", "period": "Saffarid Dynasty", "theme": "Persian Language Revival"},
    {"en": "SAMANID RENAISSANCE AT BUKHARA", "fa": "سامانیان بخارا و بوی جوی مولیان", "period": "Samanid Dynasty", "theme": "Literary Golden Age"},
    {"en": "ROUDAKI'S HARP TUNES", "fa": "چنگ رودکی؛ پدر شعر فارسی", "period": "Samanid Dynasty", "theme": "Early Poetry"},
    {"en": "BUYID BROTHERS TAKE BAGHDAD", "fa": "آل بویه و تصرف بغداد", "period": "Buyid Dynasty", "theme": "Shi'ite Hegemony"},
    {"en": "GHAZNAVID ELEPHANTS ON PARADE", "fa": "فیل‌های سلطان محمود غزنوی", "period": "Ghaznavid Empire", "theme": "Military Campaigns"},
    {"en": "BIRUNI'S MEASURING TAPE", "fa": "ابوریحان بیرونی و اندازه زمین", "period": "Medieval Islamic", "theme": "Astronomy & Geodesy"},
    {"en": "RAZI'S TEST TUBES", "fa": "زکریای رازی و کشف الکل و جوهر گوگرد", "period": "Medieval Islamic", "theme": "Chemistry & Medicine"},
    {"en": "KHWARAZMI'S ALGEBRA CLASS", "fa": "خوارزمی و تولد جبر و الگوریتم", "period": "Medieval Islamic", "theme": "Mathematics"},
    {"en": "TUGHRIL'S TURKISH DELIGHT", "fa": "طغرل‌بیک و ظهور امپراتوری سلجوقی", "period": "Seljuk Empire", "theme": "Nomadic Rise"},
    {"en": "ALP ARSLAN AT MANZIKERT", "fa": "آلب‌ارسلان و نبرد سرنوشت‌ساز ملازگرد", "period": "Seljuk Empire", "theme": "Conquest of Anatolia"},
    {"en": "MALIK SHAH'S PEAK EMPIRE", "fa": "ملکشاه سلجوقی در اوج اقتدار", "period": "Seljuk Empire", "theme": "Imperial Height"},
    {"en": "NIZAM AL-MULK'S POLICY MEMO", "fa": "سیاست‌نامه خواجه نظام‌الملک", "period": "Seljuk Empire", "theme": "Statecraft"},
    {"en": "NIZAMIYA SCHOOLS OF THOUGHT", "fa": "نظامیه‌ها و پرورش دانشمندان", "period": "Seljuk Empire", "theme": "Education"},
    {"en": "KHAYYAM'S WINE & CALENDAR", "fa": "خیام، تقویم جلالی و رباعیات", "period": "Seljuk Empire", "theme": "Poetry & Calendar"},
    {"en": "ASSASSINS OF ALAMUT", "fa": "حسن صباح و رازهای قلعه الموت", "period": "Ismaili State", "theme": "Secret Orders"},
    {"en": "HULAGU DROPS THE CURTAIN", "fa": "هولاکوخان و سقوط خلافت بغداد", "period": "Ilkhanid Empire", "theme": "Mongol Conquest"},
    {"en": "MARAGHEH OBSERVATORY TELESCOPES", "fa": "رصدخانه مراغه و خواجه نصیر طوسی", "period": "Ilkhanid Empire", "theme": "Science"},
    {"en": "GHAZAN KHAN'S ISLAMIC TURN", "fa": "غازان‌خان و اسلام‌آوری ایلخانان", "period": "Ilkhanid Empire", "theme": "Conversion & Reforms"},
    {"en": "RASHID AL-DIN'S COMPENDIUM", "fa": "جامع‌التواریخ رشیدالدین فضل‌الله", "period": "Ilkhanid Empire", "theme": "World History"},
    {"en": "SOLTANIYEH DOME UNDER STARS", "fa": "گنبد دوپوسته سلطانیه زنجان", "period": "Ilkhanid Empire", "theme": "Architecture"},
    {"en": "SARBEDARAN REBELS OF SABZEVAR", "fa": "قیام سربداران سبزوار: سر به دار می‌دهیم", "period": "Post-Mongol", "theme": "Social Uprising"},
    {"en": "TIMUR'S SKULL PYRAMIDS", "fa": "تیمور لنگ و کله‌منارهای مخوف", "period": "Timurid Empire", "theme": "Conquests"},
    {"en": "SHAHRUKH'S HERAT RENAISSANCE", "fa": "شاهرخ تیموری و رنسانس هرات", "period": "Timurid Empire", "theme": "Culture & Peace"},
    {"en": "GOHARSHAD'S MOSQUE OF GOLD", "fa": "مسجد گوهرشاد مشهد و معماری تیموری", "period": "Timurid Empire", "theme": "Architecture"},
    {"en": "ULUGH BEG'S ASTRONOMICAL TABLES", "fa": "زیج الغ‌بیگ و رصد ستارگان سمرقند", "period": "Timurid Empire", "theme": "Astronomy"},
    {"en": "BEHZAD'S MINIATURE BRUSH", "fa": "قلم‌موی جادویی کمال‌الدین بهزاد", "period": "Timurid & Safavid", "theme": "Miniature Art"},
    {"en": "JAMI'S SEVEN THRONES", "fa": "هفت اورنگ جامی؛ خاتم‌الشعرا", "period": "Timurid Era", "theme": "Poetry"},
    {"en": "SHAH ISMAIL'S CHALDIRAN STAND", "fa": "شاه اسماعیل یکم و حماسه چالدران", "period": "Safavid Empire", "theme": "Battle of Chaldiran"},
    {"en": "SHAH TAHMASP'S FIFTY-YEAR REIGN", "fa": "شاه طهماسب یکم و نیم قرن سلطنت در قزوین", "period": "Safavid Empire", "theme": "Treaty of Amasya"},

    # 101 to 150
    {"en": "JULFA SILK TRADE IN ISFAHAN", "fa": "ارامنه جلفا و جاده ابریشم صفوی", "period": "Safavid Empire", "theme": "Trade & Minority Communities"},
    {"en": "PORTUGUESE EXPULSION FROM HORMUZ", "fa": "اخراج پرتغالی‌ها از تنگه هرمز و جزیره قشم", "period": "Safavid Empire", "theme": "Imam Quli Khan"},
    {"en": "SHAH ABBAS'S CARAVANSERAIS", "fa": "۹۹۹ کاروانسرای شاه عباسی", "period": "Safavid Empire", "theme": "Infrastructure"},
    {"en": "CHIHIL SUTUN MIRROR PALACES", "fa": "چهل‌ستون و بیست ستون در آب", "period": "Safavid Empire", "theme": "Palaces"},
    {"en": "SI-O-SE POL ARCHES", "fa": "سی‌وسه‌پل و زاینده‌رود همیشه زنده", "period": "Safavid Empire", "theme": "Bridges"},
    {"en": "AFGHAN SIEGE OF ISFAHAN", "fa": "سقوط اصفهان و شاه سلطان حسین بی‌اراده", "period": "Safavid Fall", "theme": "Siege of 1722"},
    {"en": "NADER SHAH CROSSES INDUS", "fa": "نادرشاه و عبور از رود سند به سوی دهلی", "period": "Afsharid Empire", "theme": "Indian Campaign"},
    {"en": "KOH-I-NOOR & PEACOCK THRONE", "fa": "تخت طاووس دهلی و کوه نور", "period": "Afsharid Empire", "theme": "Spoils of War"},
    {"en": "KALAT-E NADERI FORTRESS", "fa": "کاخ خورشید در دژ تسخیرناپذیر کلات", "period": "Afsharid Empire", "theme": "Architecture"},
    {"en": "KARIM KHAN'S VAKIL RESIDENCE", "fa": "ارگ کریم‌خان و حمام و بازار وکیل", "period": "Zand Dynasty", "theme": "Shiraz Architecture"},
    {"en": "LOTF-ALI KHAN'S TRAGIC VALOR", "fa": "لطفعلی‌خان زند؛ واپسین شوالیه شیراز", "period": "Zand Fall", "theme": "Siege of Kerman"},
    {"en": "AGHA MOHAMMAD KHAN'S TEHRAN CAPITAL", "fa": "آقامحمدخان قاجار و پایتختی طهران", "period": "Qajar Dynasty", "theme": "Founding of Capital"},
    {"en": "GOLESTAN PALACE MIRROR HALLS", "fa": "تالار آینه و کاخ گلستان طهران", "period": "Qajar Dynasty", "theme": "Palaces"},
    {"en": "TREATY OF GOLESTAN BORDER", "fa": "عهدنامه گلستان و جدایی قفقاز شمالی", "period": "Qajar Dynasty", "theme": "Russo-Persian War"},
    {"en": "ABBAS MIRZA'S NEW ARMY", "fa": "عباس‌میرزا و نظام جدید در دارالسلطنه تبریز", "period": "Qajar Dynasty", "theme": "Military Modernization"},
    {"en": "GRIBOYEDOV'S RUSSIAN EMBASSY MOB", "fa": "تسخیر سفارت روسیه و قتل گریبایدوف", "period": "Qajar Dynasty", "theme": "Diplomatic Crisis"},
    {"en": "QA'EM MAQAM'S NEGARISTAN POETRY", "fa": "قائم‌مقام فراهانی و قتل در باغ نگارستان", "period": "Qajar Dynasty", "theme": "Reform & Tragedy"},
    {"en": "HERAT SIEGE & BRITISH TREATY OF PARIS", "fa": "محاصره هرات و معاهده پاریس ۱۸۵۷", "period": "Qajar Dynasty", "theme": "Loss of Herat"},
    {"en": "NASIR AL-DIN SHAH'S EUROPEAN DIARIES", "fa": "سفرنامه‌های فرنگ ناصرالدین‌شاه", "period": "Qajar Dynasty", "theme": "European Travel"},
    {"en": "MIRZA REZA KERMANI'S PISTOL", "fa": "تپانچه میرزا رضا در ۵۰ سالگی سلطنت ناصری", "period": "Qajar Dynasty", "theme": "Assassination 1896"},
    {"en": "REUTER'S BLANK-CHECK CONCESSION", "fa": "امتیازنامه بارون رویتر؛ بزرگ‌ترین حراج جهان", "period": "Qajar Dynasty", "theme": "Concessions"},
    {"en": "TALBOT'S TOBACCO MONOPOLY CRASH", "fa": "کمپانی رژی و فتوای تحریم تنباکوی شیرازی", "period": "Qajar Dynasty", "theme": "Mass Boycott"},
    {"en": "SUGAR MERCHANTS BASTINADO PROTEST", "fa": "فلک شدن قندفروشان توسط علاءالدوله", "period": "Constitutional Revolution", "theme": "Trigger of 1905"},
    {"en": "MOZAFFAR AL-DIN SHAH'S PEN", "fa": "فرمان مشروطیت در بستر مرگ مظفرالدین‌شاه", "period": "Constitutional Revolution", "theme": "1906 Decree"},
    {"en": "SUPPLEMENTARY FUNDAMENTAL LAWS 1907", "fa": "متمم قانون اساسی و نظارت پنج مجتهد", "period": "Constitutional Revolution", "theme": "Constitution"},
    {"en": "MAJLES BOMBARDMENT BY LIAKHOV", "fa": "توپخانه لیاخوف قزاق بر بهارستان مظلوم", "period": "Constitutional Revolution", "theme": "1908 Coup"},
    {"en": "BAQER KHAN SALAR-E MELLI", "fa": "باقرخان سالار ملی بر سنگرهای خیابان تبریز", "period": "Constitutional Revolution", "theme": "Tabriz Heroes"},
    {"en": "YEPREM KHAN'S REVOLUTIONARY FORCES", "fa": "یپرم‌خان ارمنی و فتح مسلحانه تهران", "period": "Constitutional Revolution", "theme": "Military March"},
    {"en": "SHEIKH FAZLOLLAH ON TUPKHANEH GALLOWS", "fa": "بر دار رفتن شیخ فضل‌الله در میدان توپخانه", "period": "Constitutional Revolution", "theme": "Treason Trial"},
    {"en": "MORGAN SHUSTER'S STRANGLING OF PERSIA", "fa": "مورگان شوستر و اختناق ایران در گمرکات", "period": "Constitutional Revolution", "theme": "American Advisor"},
    {"en": "WWI FAMINE & OCCUPATION IN PERSIA", "fa": "قحطی بزرگ ۱۲۹۷ در اشغال بی‌طرفی ایران", "period": "WWI Era", "theme": "Great Famine"},
    {"en": "MIRZA KUCHIK KHAN'S JANGAL REPUBLIC", "fa": "میرزا کوچک‌خان و جمهوری جنگل در گیلان", "period": "Interwar Era", "theme": "Jangali Movement"},
    {"en": "COLONEL PESYAN'S KHORASAN UPRISING", "fa": "کلنل محمدتقی‌خان پسیان در سنگر مشهد", "period": "Interwar Era", "theme": "Rebellion"},
    {"en": "SAYYED ZIA'S BLACK CABINET", "fa": "سید ضیاءالدین طباطبایی و کابینه سیاه", "period": "1921 Coup", "theme": "Politics"},
    {"en": "REZA SHAH'S CORONATION IN 1926", "fa": "تاج‌گذاری رضاشاه با تاج پهلوی در کاخ گلستان", "period": "Pahlavi Era", "theme": "Coronation"},
    {"en": "UNIVERSITY OF TEHRAN FOUNDATION", "fa": "تأسیس دانشگاه تهران با طرح آندره گدار", "period": "Pahlavi Era", "theme": "Higher Education"},
    {"en": "GOHARSHAD MOSQUE KASHKUL PROTEST", "fa": "کلاه‌پهلوی، شاپو و واقعه خونین مسجد گوهرشاد", "period": "Pahlavi Era", "theme": "1935 Protest"},
    {"en": "KASHF-E HIJAB DECREE 1936", "fa": "فرمان کشف حجاب رضاشاه در دانشسرای مقدماتی", "period": "Pahlavi Era", "theme": "Social Mandate"},
    {"en": "FERDOWSI MILLENARY CELEBRATION 1934", "fa": "کنگره هزاره فردوسی و افتتاح آرامگاه طوس", "period": "Pahlavi Era", "theme": "Cultural Nationalism"},
    {"en": "ALLIED OCCUPATION AUGUST 1941", "fa": "سوم شهریور ۱۳۲۰: تهاجم غافلگیرانه متفقین", "period": "WWII Era", "theme": "Invasion & Abdication"},
    {"en": "TEHRAN CONFERENCE BIG THREE", "fa": "چرچیل، روزولت و استالین در کنفرانس تهران", "period": "WWII Era", "theme": "Tehran Conference"},
    {"en": "PISHEVARI'S DEMOCRATIC PARTY OF AZERBAIJAN", "fa": "فرقه دموکرات پیشه‌وری در آذربایجان", "period": "Post-War", "theme": "1946 Crisis"},
    {"en": "QAVAM'S MOSCOW CAVIAR DIPLOMACY", "fa": "احمد قوام و بازی شطرنج با استالین در مسکو", "period": "Post-War", "theme": "Northern Oil Concession"},
    {"en": "MOSSADEGH'S NATIONAL FRONT COALITION", "fa": "تأسیس جبهه ملی توسط محمد مصدق در بهارستان", "period": "Oil Era", "theme": "National Front"},
    {"en": "OIL NATIONALIZATION ACT OF 1951", "fa": "۲۹ اسفند ۱۳۲۹: تصویب ملی شدن صنعت نفت", "period": "Oil Era", "theme": "Historic Legislation"},
    {"en": "THE HAGUE COURT OIL VICTORY", "fa": "پیروزی مصدق و ایران در دیوان دادگستری لاهه", "period": "Oil Era", "theme": "International Law"},
    {"en": "30 TIR UPRISING 1952", "fa": "قیام ۳۰ تیر ۱۳۳۱ و بازگشت پیروزمندانه مصدق", "period": "Oil Era", "theme": "Popular Revolt"},
    {"en": "KASHANI & MOSSADEGH FRACTURE", "fa": "اختلاف آیت‌الله کاشانی و مصدق و جدایی یاران", "period": "Oil Era", "theme": "Political Schism"},
    {"en": "KERMIT ROOSEVELT'S SAFE-HOUSE", "fa": "کرمیت روزولت و چمدان‌های دلار کودتای ۲۸ مرداد", "period": "1953 Coup", "theme": "CIA Operation TPAJAX"},
    {"en": "GENERAL ZAHEDI'S TANK PARADE", "fa": "سپهبد فضل‌الله زاهدی سوار بر تانک کودتا", "period": "1953 Coup", "theme": "Military Coup"}
]
