#!/usr/bin/env python3
"""Check the two shipped reading lists: the shelves the Reading List panel reads.

    python3 Tools/check_readings.py

    python3 Tools/check_readings.py Web/data/readings.js \\
        Web/courses/iran-in-world-politics/data/readings.js

`Web/data/readings.js` is generated by `Tools/make_readings.py`, so a generator
bug would otherwise ship silently — `check_web.js` loads `i18n.js`, the banks and
`editions.js` and never opens either shelf. The course list at
`Web/courses/iran-in-world-politics/data/readings.js` is authored by hand from the
PDFs themselves and has no generator and no other guard at all.

Neither file can be read with `json.loads`: they are JS, and the course entries
write `year: 1982` unquoted and `null` where a PDF states no year. So the file is
evaluated by `node` in a context whose only global is a bare `window`, and the
one assignment it makes is read back as JSON. The marker is not hard-coded —
the file's own global is whatever it defines, and it is reported — but exactly one
assignment is required, because two would mean the panel is reading one list and
this checker the other.

Counts are asserted exactly. They are the size of a fixed corpus, not an
incidental total: MAIN's shelf is 91 — its own 49 books from `corpus_manifest.json`
plus the 42 readings of every course whose bank MAIN has absorbed, appended by
`Tools/make_readings.py` (its `COURSE_SHELVES` is the registry, and it asserts each
course's count itself, so this 91 is the second lock on the same door) — and IR4595
still sets 42 of its own. If a corpus legitimately changes, change the number here
in the same commit and say so.

Exit status is 1 if any ERROR was found, 0 otherwise. Warnings never fail a run.
Read-only. Nothing here writes to a shelf.
"""

import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# path -> (expected entries, a word for what the file is)
# MAIN's 91 is 49 corpus books + 42 absorbed course readings; the course's own file
# is unchanged at 42, because absorbing is one-way and the course is never touched.
SHELVES = [
    ("Web/data/readings.js", 91, "MAIN"),
    ("Web/courses/iran-in-world-politics/data/readings.js", 42, "IR4595"),
]

PERSIAN = re.compile(r"[؀-ۿ]")

ERRORS = []
WARNINGS = []
NOTES = []


def error(msg):
    ERRORS.append(msg)


def warn(msg):
    if msg not in WARNINGS:
        WARNINGS.append(msg)


def note(msg):
    if msg not in NOTES:
        NOTES.append(msg)


# ── Reading ──────────────────────────────────────────────────────────────────

# `window` is the only thing these files touch, so a context with a bare object
# for it is enough to evaluate them. Exactly one key must land on it.
READER = (
    "const fs=require('fs'),vm=require('vm');"
    "const ctx={window:{}};"
    "vm.createContext(ctx);"
    "vm.runInContext(fs.readFileSync(process.argv[1],'utf8'),ctx,"
    "{filename:process.argv[1]});"
    "const k=Object.keys(ctx.window);"
    "if(k.length!==1){process.stderr.write('expected exactly one window.<GLOBAL> "
    "assignment, saw '+JSON.stringify(k));process.exit(3);}"
    "process.stdout.write(JSON.stringify({name:k[0],value:ctx.window[k[0]]}));"
)


def load(path):
    """Evaluate one shelf file with `node` and hand back (global name, value)."""
    try:
        out = subprocess.run(["node", "-e", READER, path],
                             capture_output=True, text=True)
    except FileNotFoundError:
        raise ValueError(
            "`node` is not on PATH — this checker evaluates the shelf files the "
            "way the browser does, which needs node")
    if out.returncode != 0:
        raise ValueError("node could not evaluate %s: %s"
                         % (path, (out.stderr or out.stdout).strip()))
    try:
        got = json.loads(out.stdout)
    except ValueError:
        raise ValueError("node printed something that is not JSON for %s: %r"
                         % (path, out.stdout[:200]))
    return got["name"], got["value"]


# ── Per-shelf checks ─────────────────────────────────────────────────────────


def check_shelf(path, expected, label):
    """One shelf: the count, the group shape, and that no row is a blank."""
    name, groups = load(path)
    note("%s: `window.%s`, %d group(s)" % (label, name, len(groups or [])))

    if not isinstance(groups, list) or not groups:
        error("%s: %s is not a non-empty array — the panel would open empty"
              % (label, name))
        return

    total = 0
    titles = {}
    for gi, g in enumerate(groups):
        where = "%s group %d" % (label, gi + 1)
        head = g.get("group") if isinstance(g, dict) else None
        if not isinstance(head, dict):
            error("%s: no `group` label object" % where)
        else:
            for lang in ("en", "fa"):
                val = str(head.get(lang) or "").strip()
                if not val:
                    error("%s: `group.%s` is empty — one language would show a "
                          "blank heading" % (where, lang))
                elif lang == "en" and PERSIAN.search(val):
                    warn("%s: `group.en` %r carries Persian script" % (where, val))
                elif lang == "fa" and not PERSIAN.search(val):
                    warn("%s: `group.fa` %r carries no Persian script — a label "
                         "left in English reads as untranslated" % (where, val))
            if isinstance(head.get("en"), str):
                where = "%s (%s)" % (where, head["en"])

        items = g.get("items") if isinstance(g, dict) else None
        if not isinstance(items, list) or not items:
            error("%s: `items` is not a non-empty array" % where)
            continue
        total += len(items)

        for ii, it in enumerate(items):
            at = "%s row %d" % (where, ii + 1)
            if not isinstance(it, dict):
                error("%s: not an object" % at)
                continue
            for field in ("title", "author"):
                if not str(it.get(field) or "").strip():
                    error("%s: empty %s — the row would print a blank line"
                          % (at, field))
            title = str(it.get("title") or "").strip()
            if title:
                titles.setdefault(title, []).append(at)
            if it.get("year") is None:
                note("%s: no year (author state, not a defect)" % at)

    if total != expected:
        error("%s: %d entries, expected %d — the shelf and this checker disagree "
              "about the corpus" % (label, total, expected))
    else:
        note("%s: %d entries, as expected" % (label, total))

    dupes = {t: ws for t, ws in titles.items() if len(ws) > 1}
    if dupes:
        warn("%s: %d title(s) appear more than once (%s)"
             % (label, len(dupes), "; ".join(sorted(dupes)[:4])))


def main():
    args = sys.argv[1:]
    if args:
        shelves = [(p, None, os.path.splitext(os.path.basename(p))[0]) for p in args]
    else:
        shelves = SHELVES

    failed = False
    for path, expected, label in shelves:
        full = path if os.path.isabs(path) else os.path.join(ROOT, path)
        if not os.path.exists(full):
            error("%s: %s does not exist" % (label, path))
            failed = True
            continue
        try:
            check_shelf(full, expected, label)
        except (ValueError, OSError) as exc:
            error("%s: %s" % (label, exc))
            failed = True

    for m in NOTES:
        print("  %s" % m)
    if WARNINGS:
        print("\n%d warning(s):" % len(WARNINGS))
        for m in WARNINGS:
            print("  ! %s" % m)
    if ERRORS or failed:
        print("\n%d error(s):" % len(ERRORS))
        for m in ERRORS:
            print("  X %s" % m)
        print("\nFAILED")
        return 1
    print("\nOK — no errors%s" % (" (%d warning(s))" % len(WARNINGS) if WARNINGS else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
